@echo off
echo Running Python MCB Benchmark...
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
call venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Starting Benchmark...
python benchmark.py
pause